export const palavras = [
  "BRASIL", "ARGENTINA", "PORTUGAL", "ALEMANHA", "FRANCA", 
  "ESPANHA", "ITALIA", "JAPAO", "CHINA", "CANADA", 
  "MEXICO", "AUSTRALIA", "EGITO", "RUSSIA", "INDIA", 
  "ANGOLA", "CHILE", "COLOMBIA", "DINAMARCA", "GRECIA", 
  "HOLANDA", "INGLATERRA", "IRLANDA", "JAMAICA", "NORUEGA", 
  "PERU", "SUECIA", "SUICA", "TURQUIA", "URUGUAI"
];